### PR TITLE
Change "persistance" to "persistence"

### LINKED ISSUE #4: "persistence" is misspelled on website
Via deepstreamIO/golden-layout#294

### PR DESCRIPTION
**Pull request by jdanford**
Fixes #4

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hiyas, I think the `hbs` and `.md` template files need adjusting too. My local build doesn't seem to want to work all that well, but `grunt build` should show up the files (though it seems to want to delete a load of things too...) I'll see if I can work out what's going on, but the html files are all derived files...

**Comment by jdanford** [comment]
> I think the hbs and .md template files need adjusting too

Which files are you referring to?

**Comment by mattgodbolt** [comment]
Whoops! My mistake: I totally misread your PR! All looks good - thanks! *blush*

**Comment by mattgodbolt** [comment]
And fix pushed to the site (will take a while to update). Thanks for your patience!

**Pull request merged**
